def training_args(parser):
    parser.add_argument('--gtr_data_dir', type=str, default='./datasets/train/faster/')
    parser.add_argument('--gtd_data_dir', type=str, default='./datasets/train/depth_v2/faster/')
    parser.add_argument('--val_gtr_data_dir', type=str, default='./datasets/test/synthetic/')
    parser.add_argument('--val_gtd_data_dir', type=str, default='./datasets/test/synthetic/depth_test/')
    parser.add_argument('--plotdir', type=str, default='./depth_ref_results/train_plots')
    parser.add_argument('--weights_dir', type=str, default='./depth_ref_results/weights')
    parser.add_argument('--log_dir', type=str, default='./depth_ref_results/log_files', help='....')
    parser.add_argument('--gray_mode', type=bool, default=True, help='image transforms')
    parser.add_argument('--downsample', default=True, help='True if downsample the input')
    parser.add_argument('--dwratio', type=int, default=2, help='downsample ratio')
    parser.add_argument('--transforms', type=bool, default=True, help='image transforms')
    parser.add_argument('--n_features', type=int, default=64, help='...')
    parser.add_argument('--inp_ch', type=int, default=1, help='...')
    parser.add_argument('--num_frames', type=int, default=21, help='...')
    parser.add_argument('-batch_size', type=int, default=6, help='....')
    parser.add_argument('-save_period', type=int, default=1000, help='....')
    parser.add_argument('-total_epochs', type=int, default=1000, help='....')
    parser.add_argument('-start_epoch', type=int, default=0, help='....')
    parser.add_argument('-log_every', type=int, default=1, help='....')
    parser.add_argument('--visualize', type=bool, default=True, help='visualization during validation')
    parser.add_argument('--save_every_epochs', type=int, default=50,
                        help='save checkpoint every N epochs regardless of best')
    parser.add_argument('--seed', type=int, default=112)


def testing_args(parser):
    parser.add_argument('--test_gtr_data_dir', type=str, default='./datasets/test/synthetic')
    parser.add_argument('--test_gtd_data_dir', type=str, default='./datasets/test/synthetic/depth_test/')
    parser.add_argument('--plotdir', type=str, default='./depth_ref_results/test_plots')
    parser.add_argument('--folder_name', type=str, default='', help='folder name')
    parser.add_argument('--gray_mode', type=bool, default=True, help='image transforms')
    parser.add_argument('--downsample', default=True, help='True if downsample the input')
    parser.add_argument('--dwratio', type=int, default=4, help='downsample ratio')
    parser.add_argument('--image_type', type=str, default='*.png', help='*.png or *.tiff etc.')
    parser.add_argument('--workers', type=int, default=0, help='dataloader cpu workers')
    parser.add_argument('--transforms', type=bool, default=False, help='image transforms')

    parser.add_argument('--n_features', type=int, default=64, help='...')
    parser.add_argument('--inp_ch', type=int, default=1, help='...')
    parser.add_argument('--future_frames', type=int, default=30, help='...')
    parser.add_argument('--past_frames', type=int, default=30, help='...')
    parser.add_argument('--num_frames', type=int, default=61, help='...')
    parser.add_argument('--patch_size', type=int, default=128, help='patch size of each frame during training')
    parser.add_argument('--num_of_cbam', type=int, default=16, help='number of cbam pairs')
    parser.add_argument('--num_of_heads', type=int, default=1, help='number of heads in multi head attention')

    parser.add_argument('--model_name', type=str, default='depth_ref', help='model name')
    parser.add_argument('-batch_size', type=int, default=1, help='....')
    parser.add_argument('--weights_path', type=str, default='./depth_ref_results/weights_depth_best.pth')
    parser.add_argument('--save_path', type=str, default='./depth_ref_results/testing_results/')
    parser.add_argument('--visualize', type=bool, default=False, help='visualization during validation')

def sensor_args(parser):
    parser.add_argument('--fps', default=1000, help='The cameras operational frame rate')
    parser.add_argument('--rep_rate', default=2.25e6, help='The repition rate of the laser')
    parser.add_argument('--energy_per_pulse', default=3.219e-10, help='The pulse energy of the laser')
    parser.add_argument('--pulse_width', default=1e-9, help='width of the laser pulse')
    parser.add_argument('--spad_q_base_efficiency', default=0.18, help='The effective quantum efficiency of the SPAD')
    parser.add_argument('--target_range', default=15, help='The range to the target')
    parser.add_argument('--fibre_core', default=550e-6, help='The size of the fibre core used for illumination')
    parser.add_argument('--illum_lens', default=8e-3, help='The focal length of the illuminating lens')
    parser.add_argument('--effictive_pix_size_x', default=9.2e-6,
                        help='The effective size of the x pixels including fill factor')
    parser.add_argument('--effictive_pix_size_y', default=9.2e-6,
                        help='The effective size of the y pixels including fill factor')
    parser.add_argument('--f_no', default=2, help='The f number of the lens')
    parser.add_argument('--dark_count_rate', default=126, help='dark current rate in Hz')
    parser.add_argument('--solar_background_per_meter', default=0.0002, help='Background meter reading')
    parser.add_argument('--C_atm', default=10 ** (-1 * (7e-4 / 10.0)),
                        help='The transmission coefficent of the atmosphere')
    parser.add_argument('--wavelength', default=671e-9, help='Wavelength of pulse laser')
    parser.add_argument('--expand', default=1, help='Exapnd the actual time values')
    parser.add_argument('--jitter', default=220e-12, help='Jitter value of the laser unit')
    parser.add_argument('--min_depth_in_time', default=0, help='Minimum depth values')
    parser.add_argument('--c_speed', default=3e8, help='Speed of the light')
    parser.add_argument('--plank', default=6.626e-34, help='Planks constant')
    parser.add_argument('--scale_min', default=0.01, help='minimum distance')
    parser.add_argument('--scale_max', default=60, help='maximum distance < 62')
